FROM registry.head-labs.com/ton/ton-base:v0

ENV PUBLIC_IP 94.130.163.226
ENV CONFIG https://test.ton.org/ton-global.config.json
ENV CONSOLE_PORT 46731
ENV LITESERVER true
ENV LITE_PORT 46732

ENTRYPOINT ["/var/ton-work/db/init.sh"]
